theme: jekyll-theme-midnight

# Q-Tracker Cirus Lab

Q-Tracker is originally a High School Project created by Admins of Cirus Lab.
It's completly coded in python along with mysql.(Tkinter For GUI)

## Description
  Q-tracker is a mysql based python program which focuses on database management in Quarantine Centers. It offers a simple GUI solution to add and delete details p new patients ,and also alert on the new details.
  



## Cirus Lab

```markdown   

# Python Programming
## Android Development
### AI and Web Development

- Non profit community
- Formed By Bharath Krishna

#Senior Developers
1. Adithya Krishnan. fal3n.4ngel Github/ Insta
2. Bharath Krishna. Th3_nuclear_rebel Insta

```
